// everyone else's likes should reference Jennie's UID

const seedUserData = [
  // main character - 30 year old software engineer living in NYC who enjoys cooking and also outgoing!
  {
    userId: '',
    email: 'jennie.kim.0514@gmail.com',
    firstName: 'Jennie',
    lastName: 'Kim',
    pronouns: ['she'],
    interests: [
      'Computer programming',
      'Cooking',
      'Roller skating',
      'Urban exploration',
      'Knife making',
    ],
    profilePicture: '',
    // reference Hailey and Darcie's UID
    likes: [],
  },
  {
    userId: '',
    email: 'cara.o.wade@hotmail.com',
    firstName: 'Cara',
    lastName: 'Wade',
    pronouns: ['they'],
    interests: [
      'Cooking',
      'Gambling',
      'Genealogy',
      'Glassblowing',
      'Computer programming',
    ],
    profilePicture: '',
    likes: [],
  },
  {
    userId: '',
    email: 'mk01234@gmail.com',
    firstName: 'Markus',
    lastName: 'Kirkland',
    pronouns: ['he'],
    interests: ['Cooking', 'Knitting', 'Driving', 'Fishing', 'Flag football'],
    profilePicture: '',
    likes: [],
  },
  {
    userId: '',
    email: 'abu.malone@gmail.com',
    firstName: 'Abubakr',
    lastName: 'Malone',
    pronouns: ['they'],
    interests: [
      'Cooking',
      'Mountain biking',
      'Mountaineering',
      'Mushroom hunting',
      'Mycology',
    ],
    profilePicture: '',
    likes: [],
  },
  {
    userId: '',
    email: 'lesss.callahan@gmail.com',
    firstName: 'Leslie',
    lastName: 'Callahan',
    pronouns: ['she', 'he'],
    interests: [
      'Cooking',
      'Skydiving',
      'Taekwondo',
      'Vehicle restoration',
      'Water sports',
    ],
    profilePicture: '',
    likes: [],
  },
  {
    userId: '',
    email: 'sam.ayers.0987@gmail.com',
    firstName: 'Sameera',
    lastName: 'Ayers',
    pronouns: ['undisclosed'],
    interests: [
      'Cooking',
      'Beekeeping',
      'Sports',
      'Stand-up comedy',
      'Listening to music',
    ],
    profilePicture: '',
    likes: [],
  },
  {
    userId: '',
    email: 'vijay.e.vasquez@hotmail.com',
    firstName: 'Vijay',
    lastName: 'Vasquez',
    pronouns: ['he'],
    interests: [
      'Cooking',
      'Ghost hunting',
      'Hiking',
      'World building',
      'Astronomy',
    ],
    profilePicture: '',
    likes: [],
  },
  {
    userId: '',
    email: 'lejamcc777@gmail.com',
    firstName: 'Leja',
    lastName: 'Mcclure',
    pronouns: ['she'],
    interests: ['Cooking', 'Sewing', 'Singing', 'Sketching', 'Soapmaking'],
    profilePicture: '',
    likes: [],
  },
  // soul mate found!
  {
    userId: '',
    email: 'mathews.hailey.34@gmail.com',
    firstName: 'Hailey',
    lastName: 'Mathews',
    pronouns: ['they'],
    interests: [
      'Cooking',
      'Knife making',
      'Computer programming',
      'Urban exploration',
      'Roller skating',
    ],
    profilePicture: '',
    likes: [],
  },
  // almost soul mate
  {
    userId: '',
    email: 'dardarcie.wong@hotmail.com',
    firstName: 'Darcie',
    lastName: 'Wong',
    pronouns: ['he'],
    interests: [
      'Knife making',
      'Cooking',
      'Computer programming',
      'Archery',
      'Urban exploration',
    ],
    profilePicture: '',
    likes: [],
  },
];
